# Generated by Selenium IDE
import os
from datetime import datetime

import pytest

from selenium import webdriver
from selenium.webdriver.common.by import By


caminho_print = 'C:/Users/Anderson/PycharmProjects/fts132_inicial/3_Teste_Web/prints/' \
                + datetime.now().strftime('%Y-%m-%d %H-%M-%S') + '/'

class TestConsultaProdutoPet():

    def before_all(self):
    try:
        os.mkdir(caminho_print)
    except:
        print ('A pasta já existia')

    def setup_method(self, method):
        self.driver = webdriver.Chrome('C://Users//Anderson//PycharmProjects//fts132_inicial//3_Teste_Web//drivers//chromedriver.exe')
        self.driver.implicitly_wait(30)
        self.driver.maximize_window()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    #Definição do Teste
    @pytest.mark.parametrize('id, termo, produto, preco', [
        ('1', 'coleira azul', 'Coleira Ferplast Dayton Fantasy Azul para Cães', 'R$ 79,99'),
        ('2', 'coleira rosa', 'Coleira Zee.Dog NeoPro Bubblegum Rosa para Cães', 'R$ 89,00'),
    ])
    def teste_testeWeb(self, id, termo, produto, preco):

        self.driver.get("https://www.petz.com.br/")
        self.driver.get_screenshot_as_file(f'{caminho_print}teste {id} - passo 1 - home.jpeg')

        self.driver.set_window_size(1680, 1011)
        self.driver.find_element(By.ID, "search").click()
        self.driver.find_element(By.ID, "search").clear()
        self.driver.find_element(By.ID, "search").send_keys(termo)
        self.driver.get_screenshot_as_file(f'{caminho_print}teste {id} - passo 2 - item_pesquisa.jpeg')
        self.driver.find_element(By.CSS_SELECTOR, ".custom-icon").click()

        #self.driver.find_element(By.ID, "search").send_keys(Keys.ENTER)
        #element = self.driver.find_element(By.CSS_SELECTOR, ".link-label")
        #actions = ActionChains(self.driver)
        #actions.move_to_element(element).perform()
        #element = self.driver.find_element(By.LINK_TEXT, "Gatos")
        #actions = ActionChains(self.driver)
        #actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".liProduct:nth-child(2) > #produto-href .product-img").click()
        #assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == produto
        self.driver.get_screenshot_as_file(f'{caminho_print}teste {id} - passo 3 - comparando nome item.jpeg')

        #assert self.driver.find_element(By.CSS_SELECTOR, ".current-price-left > strong").text == preco
        self.driver.get_screenshot_as_file(f'{caminho_print}teste {id} - passo 4 - comparando preço do item.jpeg')

        self.driver.find_element(By.ID, "adicionarAoCarrinho").click()
        #assert self.driver.find_element(By.CSS_SELECTOR, "#cart-item-99802 > .cart-item-detail > div:nth-child(2)").text == "Coleira Ferplast Dayton Fantasy Azul para Cães"
        #assert self.driver.find_element(By.CSS_SELECTOR, "#cart-item-99802 > .fn-wb").text == "94,99"
